package io.github.sh0inx.dragoncancel;

public enum Substring {
    HEXCOLORBRIGHT,
    HEXCOLORDARK,
    HIGHLIGHTCOLOR,
    LOWLIGHTCOLOR,
    DRAGONCANCEL,
    DRAGON,
    CANCEL,
    TITLEPREFIX,
    TITLESUFFIX,
    PREFIXPLUGINNAME,
    PREFIXINSIGNIA,
    MESSAGEPREFIX,
    DRAGONCANCELTITLE,
    DRAGONCANCELSUBTITLE,
    CONSOLEDECORATOR
}