# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.0.0
      with:
        distribution: temurin
        java-version: 8
        cache: gradle
    - name: Grant execute permission for gradle
      run: chmod +x gradlew
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: "DragonCancel"
        path: "build/libs/dragonCancel-*.jar"
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3.1.3
        id: version
        with:
          file: "build.gradle.kts"
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: "DragonCancel"
          path: "build/libs/dragonCancel-*.jar"
  release:
    if: |
      contains(github.event.commits[0].message, 'release')
      && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
