# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v3.0.0
      with:
        distribution: temurin
        java-version: 8
        cache: gradle
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission for gradle
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifacts
      uses: "actions/upload-artifact@v2.2.3"
      with:
        name: "dragonCancelLite"
        path: "build/libs/dragonCancelLite-*.jar"
        
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/upload-artifact@v3.1.3
       with:
          name: "dragonCancelLite"
          path: "build/libs/dragonCancelLite-*.jar"

  nightly:
    if: |
      contains(github.event.commits[0].message, 'beta')
      || contains(github.event.commits[0].message, 'alpha')
      || contains(github.event.commits[0].message, 'nightly')
      && github.ref == 'refs/heads/main'
    name: Deploy nightly
    runs-on: ubuntu-latest
    steps:
      - name: Nigtly Build Release
        uses: WebFreak001/deploy-nightly@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/sh0inx/Dragon-Cancel/releases/126317560/assets{?name,label}
          release_id: 126317560
          asset_path: ./dragonCancelLite-*.jar
          asset_name: dragonCancelLite-*-$$.jar
          asset_content_type: application/zip
          max_releases: 1

  release:
    if: |
      contains(github.event.commits[0].message, 'release')
      && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 4U7mK5Ez
          modrinth-token: ${{ secrets.MODRINTH_PAT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{steps.github_release.outputs.changelog}}
