# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.0.0
      with:
        distribution: temurin
        java-version: 8
        cache: gradle
    - name: Grant execute permission for gradle
      run: chmod +x gradlew
    - name: Build with Gradle
      run: gradle build
    - name: Upload artifacts
      uses: "actions/upload-artifact@v2.2.3"
      with:
        name: "DragonCancel"
        path: "build/libs/dragonCancel-*.jar"
  upload:
    needs: build
    runs-on: ubuntu-latest
    if: "contains(github.event.commits[0].message, 'version bump')"
    steps:
      - uses: actions/checkout@v2
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
        with:
          file: "build.gradle.kts"
      - uses: actions/download-artifact@v3.0.2
        with:
          name: "DragonCancel"
          path: "./"
